<h1>Books</h1>

<a href="/index.php?route=book/showCart">Show cart</a>

<br><br>

<?php foreach ($pagination->buttons as $button) :
    if ($button->isActive) : ?>
        <a href = '/books/<?=$button->page?>'><?=$button->text?></a>
    <?php else : ?>
        <span style="color:#555555"><?=$button->text?></span>
    <?php endif;
endforeach; ?>

<br><br>
<?php foreach ($books as $book) : ?>
    Title: <a href="/book-<?=$book['id']?>.html"><?=$book['title']?></a> <br/></b>
    Description: <?=$book['description']?> <br/>
    Price: <?=$book['price']?> <br/>
    Created: <?=$book['created']?> <br/>
    <a href="/cart/add/<?=$book['id']?>">Add to cart</a>

    <?php if (Session::has('user')): ?>
        <a href="/books/edit/<?=$book['id']?>">Edit</a>
    <?php endif;?>
    <hr/>
<?php endforeach;?>