<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MVC site</title>
</head>
<body>

    <a href="/">Home</a>
    <a href="/about">About</a>
    <a href="/books">Books</a>
    <a href="/contact">Contact</a>
    <?php if (Session::has('user')): ?>
        <a href="/logout">Logout</a>
    <?php else: ?>
        <a href="/login">Login</a>
    <?php endif ?>


    <hr/>

    <?=$content?>

</body>
</html>